project_name: ring cable lug-yolo_auto
dataset_name: ring cable lug-yolo
dataset_path: dataset/ring cable lug-yolo
output_dir: runs/detect/ring cable lug-yolo_auto
data_yaml_path: configs/models/data_ring cable lug-yolo.yaml
training_config:
  model: basemodels/yolo26n.pt
  epochs: 150
  imgsz: 640
  batch: 16
  workers: 8
  device: '0'
  patience: 30
  save: true
  save_period: -1
  cache: false
  exist_ok: false
  pretrained: true
  optimizer: AdamW
  verbose: true
  seed: 0
  deterministic: true
  single_cls: false
  rect: false
  cos_lr: false
  close_mosaic: 10
  resume: false
  amp: true
  fraction: 1.0
  profile: false
  lr0: 0.001
  lrf: 0.01
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 3.0
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  box: 7.5
  cls: 0.5
  dfl: 1.5
  pose: 12.0
  kobj: 1.0
  label_smoothing: 0.0
  nbs: 64
  overlap_mask: true
  mask_ratio: 4
  dropout: 0
  val: true
  plots: true
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  degrees: 0
  translate: 0.1
  scale: 0.5
  shear: 0.0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.5
  bgr: 0.0
  mosaic: 1
  mixup: 0
  copy_paste: 0.0
  copy_paste_mode: flip
  auto_augment: randaugment
  erasing: 0.4
  crop_fraction: 1.0
created_at: '2026-05-31T01:31:45.116784'
description: Auto-generated training for ring cable lug-yolo
